version: '2.2'

services:

  turbo-geth:
    image: turbo-geth:latest
    build: .
    restart: always
    command: tg --metrics --metrics.addr="0.0.0.0" --metrics.port="6060" --private.api.addr="0.0.0.0:9090" --pprof --pprof.addr="0.0.0.0" --pprof.port="6061"
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/turbogeth:/root/.local/share/turbogeth
    ports:
      - 30303:30303

  prometheus:
    image: prom/prometheus:v2.22.0
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - 9090:9090
    volumes:
      - ${TG_PROMETHEUS_CONFIG:-./cmd/prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${XDG_DATA_HOME:-~/.local/share}/tg-prometheus:/prometheus

  grafana:
    image: grafana/grafana:7.2.1
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ${TG_GRAFANA_CONFIG:-./cmd/prometheus/grafana.ini}:/etc/grafana/grafana.ini
      - ./cmd/prometheus/datasources:/etc/grafana/provisioning/datasources
      - ./cmd/prometheus/dashboards:/etc/grafana/provisioning/dashboards
      - ${XDG_DATA_HOME:-~/.local/share}/tg-grafana:/var/lib/grafana

  rpcdaemon:
    image: turbo-geth:latest
    restart: always
    command: rpcdaemon --private.api.addr="turbo-geth:9090" --http.addr="0.0.0.0" --http.vhosts="*" --http.corsdomain="*" --http.api="eth,debug,net"
    ports:
      - 8545:8545

  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx conf
      - ./nginx:/etc/nginx/conf.d
      # Certificates folder, shared with certbot
      - ./certbot/conf:/etc/letsencrypt
      # For initial CA challenge, shared with certbot
      - ./certbot/www:/var/www/certbot
      # Nginx key for basic auth
      - .htpasswd:/etc/nginx/.htpasswd
    # Reload nginx conf every 6h (Needed for certs are being renewed)
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      # Certificates folder, shared with nginx
      - ./certbot/conf:/etc/letsencrypt
      # For initial CA challenge, shared with nginx
      - ./certbot/www:/var/www/certbot
    # Check for cert renewal every 12h
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"